### ISSUE TITLE
Switch to Style Guides for Organizations

### ISSUE THREAD

**Issue by skalee** [riboseinc/oss-guides#10]
Another Rubocop Release, another breaking changes (see #9). Once more we will have to update guides across all projects (after fixing #9). Even worse — it's easy to forget about updating it in some project.

Hound features [Style Guides for Organizations](https://robots.thoughtbot.com/hound-introduces-style-guides-for-organisations) which can ease our pain. I believe we should switch to that.

The main disadvantage of Style Guides for Organizations is that it can't be disabled easily for particular repository.

Comments are very welcome.

### What needs to be done

I suppose we should host the organization's style guide in this repository (riboseinc/oss-guides). However we need to change repository layout, as Hound has some restrictrions. I recommend following layout:

```
*
|- README.adoc
|- .hound.yml (organization-wide Hound configuration, as required by Style Guides
|             for Organizations)
|- /hound <DIR> (all the other files organization-wide Hound configuration relies on)
|- /for_new_projects <DIR> (all files which are expected to be copied to newprojects,
                           and which now reside in `/styles` directory)
```

Regarding running Rubocop on developer's computer, we can reference configuration via [`remote_url`](https://rubocop.readthedocs.io/en/latest/configuration/#inheriting-configuration-from-a-remote-url). I was planning to use this feature before (see #3), but it wasn't working in Hound. Now my plan is to host common configuration here in riboseinc/oss-guides, and reference it remotely in two different ways: via Style Guides for Organizations in Hound, and via `remote_url` in local use. This may sound complicated, but is required to work universally. And I believe it will require less maintenance than our current setup.

**Comment by dewyatt** [comment]
Ping - would really like to see this move forward!

**Comment by ronaldtse** [comment]
I've enabled Hound for Organizations to point to this repo. However, it's not yet working because the `.hound.*` files are located inside a subdirectory, not at root.

@skalee @ribose-jeffreylau do you have time to put the appropriate files in the right directories to make it work? 

Thanks!

**Comment by ronaldtse** [comment]
@skalee oh and also we should update the `.hound.yml` file, perhaps we can copy the one from https://github.com/riboseinc/enmail?

**Comment by ribose-jeffreylau** [comment]
@ronaldtse Regarding copying from https://github.com/riboseinc/enmail, the `.hound.yml` files look the same to me, unless I'm misunderstanding?

Regarding making it work, are we going to proceed as detailed in https://github.com/riboseinc/oss-guides/issues/10#issuecomment-381009675 ?

**Comment by ronaldtse** [comment]
@ribose-jeffreylau yes, can you move the `.hound.yml` into root? Thanks.

**Comment by skalee** [comment]
@ribose-jeffreylau Looks great to me! I'll try updating README in the meantime. Also, adding `/.rubocop-https--*` to GitIgnore may be a good idea.

**Comment by skalee** [comment]
I've purposely introduced two code style offences into https://github.com/riboseinc/rspec-pgp_matchers/pull/24, commit https://github.com/riboseinc/rspec-pgp_matchers/pull/24/commits/7033d0667c46b43378f3d5d731b127f44dd754aa:

1) single quotes instead of double quotes (from Ribose)
2) mutable constant

Only the latter has been detected. Regarding string literals, Hound asks for single quotes, contrary to what is specified in our style guides:

https://github.com/riboseinc/oss-guides/blob/bee85d85ba42c2dfcc561b4c3b36d494c8bee08f/hound/.rubocop.tb.yml#L339-L343

Hence, it is not working correctly.

**Comment by skalee** [comment]
Hound is open source. I'll do some investigation on how it works and how it merges configurations. Started already, but I think I'll have more time for that tomorrow rather than today.

**Comment by skalee** [comment]
Created https://github.com/houndci/hound/issues/1569.

**Comment by skalee** [comment]
Issue houndci/hound#1569 received no comments, and it doesn't like it's going to be fixed soon. Let's reduce amount of Rubocop inheritance then, see #14. Please reopen if it doesn't work well.

Sorry it took that long.
