### ISSUE TITLE
Enable organization-wide style guide in Hound CI for Metanorma, etc.

### ISSUE THREAD

**Issue by skalee** [riboseinc/oss-guides#25]
We need to set up Hound CI to use the correct style guide for Metanorma organization. This can be done on https://houndci.com/repos, and @ronaldtse must do that. Instructions below. You may want to do the same for other organizations, depending on needs.

![Zrzut ekranu 2020-01-07 o 04 15 43](https://user-images.githubusercontent.com/154287/71865958-e5028800-3104-11ea-8c05-afdde5c9565f.png)

**Comment by ronaldtse** [comment]
@skalee I can't seem to configure the .hound.yml from a different organization. Perhaps we have to fork oss-guides?

**Comment by skalee** [comment]
I think so. Funny, I thought I cannot set up the style guide for Metanorma, but apparently I can. Will try.

**Comment by skalee** [comment]
On second thought, it may be better to inherit configuration instead of forking it. This way we'll keep it in one place.

**Comment by skalee** [comment]
Let's do it this way: I'll create mirrored repositories, and changes will be propagated from this repository via GHA. Just tested that locally, it should work.

However, in order to do so, I need some help from @ronaldtse. Please do following:

1. Generate a brand new SSH key (`ssh-keygen -t rsa -b 4096` should be enough)

2. Add it to riboseinc/oss-guides repo as a secret variable named `ID_RSA` (see picture)

![Zrzut ekranu 2020-01-08 o 05 16 43](https://user-images.githubusercontent.com/154287/71950081-48a8b600-31d6-11ea-9706-dd6c5cc9d66b.png)

3. Paste here a corresponding public key

**Comment by skalee** [comment]
@ronaldtse ping.

**Comment by ronaldtse** [comment]
Done. Public key:

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCi4se5HxHHRvKtRiU4/nDy0uobxbDdKyhMco2weBPiczp5/BJXeUWyklHioy7FxaM2zSCtfhsFKCQ/iG8pNT5qaJ+KsCQYOiPhsAad42QYbMY4EbhaDxrLRDnarcrGX1yAmOZXSL1ppUTnlGVOTYPKOrBohTeY4A+QhyYHLpKeNjHjKUFs+7QC3zQtl6sz2Mkh2N4gft78kimAyAqy+W3MLsIgIsjrIIh/qmo8ow9+toEf9bmlhyk/iCEQ0HMYa7h+eF7M9nxiH/Og8NdVEYxz7fYC8WfCKRWoGcCfPImDoqKKdprYNGWVHkGSsEWsCUE24CHujBGU/IFGaSADhkX5gFNmSsps+r8EGG4AuUgE7ZE6rYWCaUmbBMXOAD+BBmBFAL1Roqilq/W4HfPPVLZO1SAyUNKMFZxu0DBeSM3ttIdcetisf5YOAjZ5+XDMKxsbrQ+ZyIqwn7cXPJxeChJImCG+YMn+NLw94jD042uB4+HWOO7oFrUfn68A4SBsdcb7mMVXL5CcPqTQjmRVYmkNGfwGfDOCgXzuDJ8relS9QkjaBgh0lWQAPQjtph83x9WdUiJaS+A0RrMaN9AyRk8E8EQKbFgOXK368l1dy+FsHWsKA/r9EM3auc2TliRyYurLK1jC5x4A/oyshl3N3KR48rpX9Kq4qUMFo589/q68BQ== oss-guides@ribose.com

```

**Comment by skalee** [comment]
It fails for some reason. On my end, everything looks correct, could you double-check on yours? Perhaps a typo or something?

For reference,

– [workflow logs](https://github.com/riboseinc/oss-guides/runs/384453812)
– [workflow definition](https://github.com/riboseinc/oss-guides/blob/5424f52f53593ca20fd5805f95a5d5c3216e5b7c/.github/workflows/propagate.yml)
– [documentation for ssh-key-action](https://github.com/shimataro/ssh-key-action)

**Comment by skalee** [comment]
Style books are correctly propagated for some time now. I suppose I may close this issue.
