### ISSUE TITLE
Line is too long. 80 characters max

### ISSUE THREAD

**Issue by CAMOBAP** [riboseinc/oss-guides#29]
80 line limit looks too small, it was required in old times for VGA resolution, but for now, I think we can easily set 100 or 120

https://raw.githubusercontent.com/riboseinc/oss-guides/master/ci/rubocop.yml

**Comment by ribose-jeffreylau** [comment]
I'm fine with going with either 100 or 120.

**Comment by ronaldtse** [comment]
Agree!

**Comment by skalee** [comment]
Done in https://github.com/riboseinc/oss-guides/pull/30, but reverted in https://github.com/riboseinc/oss-guides/pull/31.

Relevant discussion was here: https://github.com/riboseinc/oss-guides/pull/31#discussion_r595879977. TL;DR: 80 chars is a good practice. If someone wants more, he should do a per-project override.

Closing.
