### ISSUE TITLE
Rubocop: Style/CollectionMethods

### ISSUE THREAD

**Issue by skalee** [riboseinc/oss-guides#35]
https://rubystyle.guide/#map-find-select-reduce-include-size says:

> Prefer `map` over `collect`, `find` over `detect`, `select` over `find_all`, `reduce` over `inject`, `include?` over `member?` and `size` over `length`. This is not a hard requirement; if the use of the alias enhances readability, it’s ok to use it. The rhyming methods are inherited from Smalltalk and are not common in other programming languages. The reason the use of select is encouraged over find_all is that it goes together nicely with reject and its name is pretty self-explanatory.

Personally I don't see any valid reason to avoid these aliases. And in fact, we use `inject` in some of our gems.

We have this check enabled in our style guide and I propose disabling it.

**Comment by opoudjis** [comment]
Well, I don't see reason for many of the rubocop changes. This rubocop, I don't actually object to, but I don't have strong feelings.

**Comment by ronaldtse** [comment]
Agree with @skalee .

**Comment by skalee** [comment]
> Well, I don't see reason for many of the rubocop checks. :)

Many of them are coming from Thoughtbot's style guide which we have adopted. Adopting some well-received style book is a better idea than writing one from a scratch. But it doesn't mean that we can't have our overrides, and that includes disabling some checks when it makes sense.

I'm open for discussion. Also, if there are special requests for Metanorma, then I guess that can be done too. Exact solution to be chosen depending on amount and type of requested changes.
