### ISSUE TITLE
Rubocop: Layout/DotPosition

### ISSUE THREAD

**Issue by skalee** [riboseinc/oss-guides#36]
See https://docs.rubocop.org/rubocop/cops_layout.html#layoutdotposition for description of this check.

ThoughtBot's style guide specifies `trailing`, but in our style guide it has been changed in 322cb2c179a721fed382a691124185a01811cf11 to `leading` so that our style guide now matches Hound defaults rather than Thoughtbot's book. That happened without any discussion, probably due to misunderstanding.

I'm going to keep it `leading` in order to avoid another change. But I'm also opening a discussion on this setting if someone has some preference on this thing. Personally I have none.

**Comment by ribose-jeffreylau** [comment]
I admit I had a slight preference for `trailing`, but now I wouldn't mind `leading`.

Besides, there are practical advantages with `leading`: https://github.com/testdouble/standard/issues/75

**Comment by ronaldtse** [comment]
I am in the same boat as @ribose-jeffreylau 😉

**Comment by ribose-jeffreylau** [comment]
As per #67 , we'll revert to `trailing` since preference has been expressed and there is at least a discussion about it (@opoudjis  ;-)

**Comment by opoudjis** [comment]
Um... I'm really sorry, I meant "leading".

We have been doing

````
hash
  .bar
  .baz
````

for the past three years, and that's the behaviour that's recently flipped, with it now being treated as incorrect.
