### ISSUE TITLE
Rubocop: Style/TrailingCommaInArguments

### ISSUE THREAD

**Issue by skalee** [riboseinc/oss-guides#37]
See https://docs.rubocop.org/rubocop/cops_style.html#styletrailingcommainarguments for description of this check.

ThoughtBot's style guide specifies `comma` for multiline argument lists, but in our style guide it has been changed in 469568118711e296909e267f6420f67c0747f83d to `no_comma` so that our style guide now matches Hound defaults rather than Thoughtbot's book. That happened without any discussion, probably due to misunderstanding.

I'd like to change it back to `comma`, because ensuring trailing commas in multiline lists reduces diff noise. I'll wait for opinions before changing anything.

**Comment by ribose-jeffreylau** [comment]
Yes, +1 for bringing back `comma`.

**Comment by opoudjis** [comment]
More important to me that Hound and Rubocop not contradict each other. But fine

**Comment by skalee** [comment]
They shouldn't. Hound is configured to use our style guides. If they do, then it's a bug somewhere — typically in given project's `.hound.yml`.

----

I'm thinking about writing a simplistic CLI wizard which will ask a few questions (minimum Ruby version, Rails, etc.) and then template proper `.hound.yml` and `.rubocop.yml`. Re-creating configs may help when something is broken. Also such tool could be helpful if we ever have to migrate our configs for some reason.

Alternatively, we can migrate away from Hound. There are tools which run linters in GHA and then post comments. This way we could have full control over linters, their versions etc. That said, Hound works correctly as long as configuration files in the projects are correct. And it provides plenty of linters unrelated to Ruby which are potentially useful too.

**Comment by ribose-jeffreylau** [comment]
+1 for the idea of a CLI tool (to help migration of repo dot files)
