### ISSUE TITLE
Rubocop: Style/ArgumentsForwarding

### ISSUE THREAD

**Issue by skalee** [riboseinc/oss-guides#41]
I'd like to add this one to the style guide: https://docs.rubocop.org/rubocop/cops_style.html#styleargumentsforwarding.

This enforces Ruby 2.7 argument forwarding which is very nice and readable IMO:

```
# bad
def foo(*args, &block)
  bar(*args, &block)
end

# bad
def foo(*args, **kwargs, &block)
  bar(*args, **kwargs, &block)
end

# good
def foo(...)
  bar(...)
end
```

Of course this check will be disabled for projects which are meant to work on older Rubies too.

Is anyone against?

**Comment by opoudjis** [comment]
> Of course this check will be disabled for projects which are meant to work on older Rubies too.

The Metanorma stack is meant to support Ruby 2.4+, and because of an ongoing incompatibility affecting packed-mn, which is a binary distro of Metanorma, we are going to keep supporting 2.4 for a very long time. 

Therefore, changes incompatible with Ruby version < 2.7 are completely unacceptable to Metanorma.

**Comment by skalee** [comment]
Rubocop is clever enough not to suggest things which are incompatible with given project's minimum Ruby version. See: https://docs.rubocop.org/rubocop/configuration.html#setting-the-target-ruby-version.

Unless it's misconfigured, of course. But if minimum Ruby version is set incorrectly, then you should experience more awkward issues, for example suggestions to use `Regexp#match?` (added in Ruby 2.5 AFAIR).

**Comment by opoudjis** [comment]
OK. But that means that for any code I work in or interact with, this suggestion won't show up...

**Comment by skalee** [comment]
That's true. For Metanorma and most of gems maintained by Ribose it will change nothing, at least for now.
