### ISSUE TITLE
Rubocop: Style/CollectionCompact

### ISSUE THREAD

**Issue by skalee** [riboseinc/oss-guides#49]
From documentation:

> This cop checks for places where custom logic on rejection nils from arrays and hashes can be replaced with {Array,Hash}#{compact,compact!}.
>
> Examples:
>
> ```ruby
> # bad
> array.reject { |e| e.nil? }
> array.select { |e| !e.nil? }
> 
> # good
> array.compact
> 
> # bad
> hash.reject! { |k, v| v.nil? }
> hash.select! { |k, v| !v.nil? }
> 
> # good
> hash.compact!
> ```

I've found plenty of select/reject abuse of this kind in glossarist projects.

This is a new check which has been added to Rubocop recently and this is why it will be disabled by default until Rubocop 2.0 release. But I really like it and I want to enable it now — unless someone opposes.

**Comment by ribose-jeffreylau** [comment]
Opinions have been expressed and are all positive so far.  Merging PR.
