### ISSUE TITLE
 Lint/ShadowedArgument IgnoreImplicitReferences

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/oss-guides#51]
https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Lint/ShadowedArgument

> This cop has `IgnoreImplicitReferences` configuration option. It means argument shadowing is used in order to pass parameters to zero arity `super` when `IgnoreImplicitReferences` is `true`.

Can we add this?

**Comment by skalee** [comment]
+1. Anyone against?

**Comment by ronaldtse** [comment]
No problem with this.

**Comment by skalee** [comment]
I'm going to leave this one open for a few more days and then open a pull request.

**Comment by opoudjis** [comment]
Reminder.

**Comment by skalee** [comment]
Thanks! I'll get back to it tomorrow.
