### ISSUE TITLE
Cannot use rubocop config without including rubocop-rails gem

### ISSUE THREAD

**Issue by mico** [riboseinc/oss-guides#62]
Cannot use rubocop config anymore without including `rubocop-rails` gem even though I don't use rails in my project.
Because of the last commit: https://github.com/riboseinc/oss-guides/commit/4e6af688892b2c131e6d1ceeec779064e95e517c

**Comment by ronaldtse** [comment]
Most of our gems don’t use Rails. Maybe we need to differentiate which rubocop config is used for different gems. 

@ribose-jeffreylau can you help address this? Thanks.

**Comment by ribose-jeffreylau** [comment]
Hi @mico , thanks for reporting and sorry for the interruption!  The fix is now awaiting merge.
