### ISSUE TITLE
Rubocop updates

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/oss-guides#9]
Update to rubocop triggers these warnings:

````
/Users/nickn/Documents/Arbeit/upwork/ribose/asciidoctor-iso/.rubocop.tb.yml: Lint/ConditionPosition has the wrong namespace - should be Layout
Error: The `Style/TrailingCommaInLiteral` cop no longer exists. Please use `Style/TrailingCommaInArrayLiteral` and/or `Style/TrailingCommaInHashLiteral` instead.
(obsolete configuration found in /Users/nickn/Documents/Arbeit/upwork/ribose/asciidoctor-iso/.rubocop.tb.yml, please update it)
````

**Comment by skalee** [comment]
Thanks for reporting. I am on that.

Unfortunately there are more incompatibilities than just this one. And even more importantly, Hound [still uses 0.52.1](https://github.com/houndci/linters/blob/master/Gemfile.lock), hence I won't merge any backwards-incompatible change to master now.

Problem occurs in Rubocop 0.53.0 which has been released yesterday. For now, I recommend to stick to ~> 0.52.0.
